export const introduction = "4月から3月まで、各月に適した保育イベントのアイデアを紹介しています。";

export const eventData = [
    {
      id: "april",
      month: 4,
      title: "春の遠足",
      category: "遠足",
      content: "春の陽気を感じながら、自然の中で遠足に出かけましょう。",
      materials: ["お弁当", "水筒", "レジャーシート"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "may",
      month: 5,
      title: "こどもの日イベント",
      category: "行事",
      content: "こどもの日を祝って、ゲームや工作を楽しみましょう。",
      materials: ["折り紙", "のり", "はさみ"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "june",
      month: 6,
      title: "梅雨の室内遊び",
      category: "室内遊び",
      content: "雨の日でも楽しめる室内での遊びを紹介します。",
      materials: ["新聞紙", "ガムテープ", "段ボール"],
      targetAge: "2歳〜5歳",
    },
    {
      id: "july",
      month: 7,
      title: "七夕まつり",
      category: "行事",
      content: "七夕の物語に触れながら、星や宇宙について学びましょう。",
      materials: ["短冊", "折り紙", "笹の葉"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "august",
      month: 8,
      title: "夏の水遊び",
      category: "水遊び",
      content: "暑い夏にぴったりの水遊びを楽しみましょう。",
      materials: ["水着", "バケツ", "水鉄砲"],
      targetAge: "2歳〜5歳",
    },
    {
      id: "september",
      month: 9,
      title: "秋の自然探索",
      category: "自然探索",
      content: "秋の自然を楽しみながら、植物や昆虫について学びましょう。",
      materials: ["虫かご", "図鑑", "ルーペ"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "october",
      month: 10,
      title: "ハロウィンパーティー",
      category: "行事",
      content: "仮装をして、ハロウィンの雰囲気を楽しみましょう。",
      materials: ["仮装衣装", "お菓子", "飾り付け用品"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "november",
      month: 11,
      title: "秋の収穫祭",
      category: "食育",
      content: "秋に収穫された野菜や果物を楽しむ収穫祭を開催しましょう。",
      materials: ["秋の野菜", "果物", "調理器具"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "december",
      month: 12,
      title: "クリスマス会",
      category: "行事",
      content: "クリスマスソングを歌ったり、プレゼント交換をしたりしましょう。",
      materials: ["クリスマスツリー", "飾り付け用品", "プレゼント"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "january",
      month: 1,
      title: "お正月遊び",
      category: "行事",
      content: "お正月ならではの遊びで、日本の文化に触れましょう。",
      materials: ["羽根つきの羽根", "凧", "かるた"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "february",
      month: 2,
      title: "節分イベント",
      category: "行事",
      content: "節分の豆まきで、鬼を退治しましょう。",
      materials: ["豆", "鬼のお面", "マス"],
      targetAge: "3歳〜5歳",
    },
    {
      id: "march",
      month: 3,
      title: "ひなまつり",
      category: "行事",
      content: "ひな人形を飾り、ひなまつりをお祝いしましょう。",
      materials: ["ひな人形", "菱餅", "ひなあられ"],
      targetAge: "3歳〜5歳",
    },
  ];